name: Build and deploy html page into azure app service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build artifact
        run: |
          mkdir -p deploy
          cp myblog.html deploy/
          cp pradeep01.jpeg deploy/
          cd deploy/
          zip -r ../artifact.zip *
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'game01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e3c58dbc46c54f6299d0e3f6987c637e }}
          package: ./artifact.zip
